version: '3.8'

services:
  app:
    build: .
    stdin_open: true
    tty: true
    environment:
      APP_ENV: production
    ports:
      - "8084:8080"
    depends_on:
      - database
    profiles:
      - prod

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading_ace
    ports:
        - "5435:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data