// Code generated by mockery. DO NOT EDIT.

package repository

import (
	model "trading-ace/src/model"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function with given fields: task
func (_m *MockTaskRepository) CreateTask(task *model.Task) (*model.Task, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Task) (*model.Task, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(*model.Task) *model.Task); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskRepository_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - task *model.Task
func (_e *MockTaskRepository_Expecter) CreateTask(task interface{}) *MockTaskRepository_CreateTask_Call {
	return &MockTaskRepository_CreateTask_Call{Call: _e.mock.On("CreateTask", task)}
}

func (_c *MockTaskRepository_CreateTask_Call) Run(run func(task *model.Task)) *MockTaskRepository_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Task))
	})
	return _c
}

func (_c *MockTaskRepository_CreateTask_Call) Return(_a0 *model.Task, _a1 error) *MockTaskRepository_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_CreateTask_Call) RunAndReturn(run func(*model.Task) (*model.Task, error)) *MockTaskRepository_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByID provides a mock function with given fields: taskID
func (_m *MockTaskRepository) GetTaskByID(taskID int) (*model.Task, error) {
	ret := _m.Called(taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.Task, error)); ok {
		return rf(taskID)
	}
	if rf, ok := ret.Get(0).(func(int) *model.Task); ok {
		r0 = rf(taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByID'
type MockTaskRepository_GetTaskByID_Call struct {
	*mock.Call
}

// GetTaskByID is a helper method to define mock.On call
//   - taskID int
func (_e *MockTaskRepository_Expecter) GetTaskByID(taskID interface{}) *MockTaskRepository_GetTaskByID_Call {
	return &MockTaskRepository_GetTaskByID_Call{Call: _e.mock.On("GetTaskByID", taskID)}
}

func (_c *MockTaskRepository_GetTaskByID_Call) Run(run func(taskID int)) *MockTaskRepository_GetTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTaskRepository_GetTaskByID_Call) Return(_a0 *model.Task, _a1 error) *MockTaskRepository_GetTaskByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetTaskByID_Call) RunAndReturn(run func(int) (*model.Task, error)) *MockTaskRepository_GetTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByDateRange provides a mock function with given fields: from, to
func (_m *MockTaskRepository) GetTasksByDateRange(from time.Time, to time.Time) ([]*model.Task, error) {
	ret := _m.Called(from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByDateRange")
	}

	var r0 []*model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) ([]*model.Task, error)); ok {
		return rf(from, to)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) []*model.Task); ok {
		r0 = rf(from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetTasksByDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByDateRange'
type MockTaskRepository_GetTasksByDateRange_Call struct {
	*mock.Call
}

// GetTasksByDateRange is a helper method to define mock.On call
//   - from time.Time
//   - to time.Time
func (_e *MockTaskRepository_Expecter) GetTasksByDateRange(from interface{}, to interface{}) *MockTaskRepository_GetTasksByDateRange_Call {
	return &MockTaskRepository_GetTasksByDateRange_Call{Call: _e.mock.On("GetTasksByDateRange", from, to)}
}

func (_c *MockTaskRepository_GetTasksByDateRange_Call) Run(run func(from time.Time, to time.Time)) *MockTaskRepository_GetTasksByDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Time))
	})
	return _c
}

func (_c *MockTaskRepository_GetTasksByDateRange_Call) Return(_a0 []*model.Task, _a1 error) *MockTaskRepository_GetTasksByDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetTasksByDateRange_Call) RunAndReturn(run func(time.Time, time.Time) ([]*model.Task, error)) *MockTaskRepository_GetTasksByDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByUserID provides a mock function with given fields: userID
func (_m *MockTaskRepository) GetTasksByUserID(userID string) ([]*model.Task, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByUserID")
	}

	var r0 []*model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*model.Task, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []*model.Task); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetTasksByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByUserID'
type MockTaskRepository_GetTasksByUserID_Call struct {
	*mock.Call
}

// GetTasksByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockTaskRepository_Expecter) GetTasksByUserID(userID interface{}) *MockTaskRepository_GetTasksByUserID_Call {
	return &MockTaskRepository_GetTasksByUserID_Call{Call: _e.mock.On("GetTasksByUserID", userID)}
}

func (_c *MockTaskRepository_GetTasksByUserID_Call) Run(run func(userID string)) *MockTaskRepository_GetTasksByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTaskRepository_GetTasksByUserID_Call) Return(_a0 []*model.Task, _a1 error) *MockTaskRepository_GetTasksByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetTasksByUserID_Call) RunAndReturn(run func(string) ([]*model.Task, error)) *MockTaskRepository_GetTasksByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByUserIDAndType provides a mock function with given fields: userID, taskType
func (_m *MockTaskRepository) GetTasksByUserIDAndType(userID string, taskType model.TaskType) ([]*model.Task, error) {
	ret := _m.Called(userID, taskType)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByUserIDAndType")
	}

	var r0 []*model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string, model.TaskType) ([]*model.Task, error)); ok {
		return rf(userID, taskType)
	}
	if rf, ok := ret.Get(0).(func(string, model.TaskType) []*model.Task); ok {
		r0 = rf(userID, taskType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string, model.TaskType) error); ok {
		r1 = rf(userID, taskType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetTasksByUserIDAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByUserIDAndType'
type MockTaskRepository_GetTasksByUserIDAndType_Call struct {
	*mock.Call
}

// GetTasksByUserIDAndType is a helper method to define mock.On call
//   - userID string
//   - taskType model.TaskType
func (_e *MockTaskRepository_Expecter) GetTasksByUserIDAndType(userID interface{}, taskType interface{}) *MockTaskRepository_GetTasksByUserIDAndType_Call {
	return &MockTaskRepository_GetTasksByUserIDAndType_Call{Call: _e.mock.On("GetTasksByUserIDAndType", userID, taskType)}
}

func (_c *MockTaskRepository_GetTasksByUserIDAndType_Call) Run(run func(userID string, taskType model.TaskType)) *MockTaskRepository_GetTasksByUserIDAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.TaskType))
	})
	return _c
}

func (_c *MockTaskRepository_GetTasksByUserIDAndType_Call) Return(_a0 []*model.Task, _a1 error) *MockTaskRepository_GetTasksByUserIDAndType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetTasksByUserIDAndType_Call) RunAndReturn(run func(string, model.TaskType) ([]*model.Task, error)) *MockTaskRepository_GetTasksByUserIDAndType_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: task
func (_m *MockTaskRepository) UpdateTask(task *model.Task) (*model.Task, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Task) (*model.Task, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(*model.Task) *model.Task); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockTaskRepository_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - task *model.Task
func (_e *MockTaskRepository_Expecter) UpdateTask(task interface{}) *MockTaskRepository_UpdateTask_Call {
	return &MockTaskRepository_UpdateTask_Call{Call: _e.mock.On("UpdateTask", task)}
}

func (_c *MockTaskRepository_UpdateTask_Call) Run(run func(task *model.Task)) *MockTaskRepository_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Task))
	})
	return _c
}

func (_c *MockTaskRepository_UpdateTask_Call) Return(_a0 *model.Task, _a1 error) *MockTaskRepository_UpdateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_UpdateTask_Call) RunAndReturn(run func(*model.Task) (*model.Task, error)) *MockTaskRepository_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
