// Code generated by mockery. DO NOT EDIT.

package repository

import (
	model "trading-ace/src/model"

	mock "github.com/stretchr/testify/mock"

	repository "trading-ace/src/repository"
)

// MockRewardRecordRepository is an autogenerated mock type for the RewardRecordRepository type
type MockRewardRecordRepository struct {
	mock.Mock
}

type MockRewardRecordRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRewardRecordRepository) EXPECT() *MockRewardRecordRepository_Expecter {
	return &MockRewardRecordRepository_Expecter{mock: &_m.Mock}
}

// CreateRewardRecord provides a mock function with given fields: rewardRecord
func (_m *MockRewardRecordRepository) CreateRewardRecord(rewardRecord *model.RewardRecord) (*model.RewardRecord, error) {
	ret := _m.Called(rewardRecord)

	if len(ret) == 0 {
		panic("no return value specified for CreateRewardRecord")
	}

	var r0 *model.RewardRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.RewardRecord) (*model.RewardRecord, error)); ok {
		return rf(rewardRecord)
	}
	if rf, ok := ret.Get(0).(func(*model.RewardRecord) *model.RewardRecord); ok {
		r0 = rf(rewardRecord)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RewardRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.RewardRecord) error); ok {
		r1 = rf(rewardRecord)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRewardRecordRepository_CreateRewardRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRewardRecord'
type MockRewardRecordRepository_CreateRewardRecord_Call struct {
	*mock.Call
}

// CreateRewardRecord is a helper method to define mock.On call
//   - rewardRecord *model.RewardRecord
func (_e *MockRewardRecordRepository_Expecter) CreateRewardRecord(rewardRecord interface{}) *MockRewardRecordRepository_CreateRewardRecord_Call {
	return &MockRewardRecordRepository_CreateRewardRecord_Call{Call: _e.mock.On("CreateRewardRecord", rewardRecord)}
}

func (_c *MockRewardRecordRepository_CreateRewardRecord_Call) Run(run func(rewardRecord *model.RewardRecord)) *MockRewardRecordRepository_CreateRewardRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.RewardRecord))
	})
	return _c
}

func (_c *MockRewardRecordRepository_CreateRewardRecord_Call) Return(_a0 *model.RewardRecord, _a1 error) *MockRewardRecordRepository_CreateRewardRecord_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRewardRecordRepository_CreateRewardRecord_Call) RunAndReturn(run func(*model.RewardRecord) (*model.RewardRecord, error)) *MockRewardRecordRepository_CreateRewardRecord_Call {
	_c.Call.Return(run)
	return _c
}

// SearchRewardRecords provides a mock function with given fields: condition
func (_m *MockRewardRecordRepository) SearchRewardRecords(condition *repository.RewardRecordSearchCondition) ([]*model.RewardRecord, error) {
	ret := _m.Called(condition)

	if len(ret) == 0 {
		panic("no return value specified for SearchRewardRecords")
	}

	var r0 []*model.RewardRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(*repository.RewardRecordSearchCondition) ([]*model.RewardRecord, error)); ok {
		return rf(condition)
	}
	if rf, ok := ret.Get(0).(func(*repository.RewardRecordSearchCondition) []*model.RewardRecord); ok {
		r0 = rf(condition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RewardRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(*repository.RewardRecordSearchCondition) error); ok {
		r1 = rf(condition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRewardRecordRepository_SearchRewardRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchRewardRecords'
type MockRewardRecordRepository_SearchRewardRecords_Call struct {
	*mock.Call
}

// SearchRewardRecords is a helper method to define mock.On call
//   - condition *repository.RewardRecordSearchCondition
func (_e *MockRewardRecordRepository_Expecter) SearchRewardRecords(condition interface{}) *MockRewardRecordRepository_SearchRewardRecords_Call {
	return &MockRewardRecordRepository_SearchRewardRecords_Call{Call: _e.mock.On("SearchRewardRecords", condition)}
}

func (_c *MockRewardRecordRepository_SearchRewardRecords_Call) Run(run func(condition *repository.RewardRecordSearchCondition)) *MockRewardRecordRepository_SearchRewardRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*repository.RewardRecordSearchCondition))
	})
	return _c
}

func (_c *MockRewardRecordRepository_SearchRewardRecords_Call) Return(_a0 []*model.RewardRecord, _a1 error) *MockRewardRecordRepository_SearchRewardRecords_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRewardRecordRepository_SearchRewardRecords_Call) RunAndReturn(run func(*repository.RewardRecordSearchCondition) ([]*model.RewardRecord, error)) *MockRewardRecordRepository_SearchRewardRecords_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRewardRecordRepository creates a new instance of MockRewardRecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRewardRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRewardRecordRepository {
	mock := &MockRewardRecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
