// Code generated by mockery. DO NOT EDIT.

package service

import (
	model "trading-ace/src/model"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// CompleteTask provides a mock function with given fields: taskID
func (_m *MockTaskService) CompleteTask(taskID int) error {
	ret := _m.Called(taskID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_CompleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteTask'
type MockTaskService_CompleteTask_Call struct {
	*mock.Call
}

// CompleteTask is a helper method to define mock.On call
//   - taskID int
func (_e *MockTaskService_Expecter) CompleteTask(taskID interface{}) *MockTaskService_CompleteTask_Call {
	return &MockTaskService_CompleteTask_Call{Call: _e.mock.On("CompleteTask", taskID)}
}

func (_c *MockTaskService_CompleteTask_Call) Run(run func(taskID int)) *MockTaskService_CompleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTaskService_CompleteTask_Call) Return(_a0 error) *MockTaskService_CompleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_CompleteTask_Call) RunAndReturn(run func(int) error) *MockTaskService_CompleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function with given fields: userId, taskType, swapAmount
func (_m *MockTaskService) CreateTask(userId string, taskType model.TaskType, swapAmount float64) (*model.Task, error) {
	ret := _m.Called(userId, taskType, swapAmount)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string, model.TaskType, float64) (*model.Task, error)); ok {
		return rf(userId, taskType, swapAmount)
	}
	if rf, ok := ret.Get(0).(func(string, model.TaskType, float64) *model.Task); ok {
		r0 = rf(userId, taskType, swapAmount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string, model.TaskType, float64) error); ok {
		r1 = rf(userId, taskType, swapAmount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskService_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - userId string
//   - taskType model.TaskType
//   - swapAmount float64
func (_e *MockTaskService_Expecter) CreateTask(userId interface{}, taskType interface{}, swapAmount interface{}) *MockTaskService_CreateTask_Call {
	return &MockTaskService_CreateTask_Call{Call: _e.mock.On("CreateTask", userId, taskType, swapAmount)}
}

func (_c *MockTaskService_CreateTask_Call) Run(run func(userId string, taskType model.TaskType, swapAmount float64)) *MockTaskService_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.TaskType), args[2].(float64))
	})
	return _c
}

func (_c *MockTaskService_CreateTask_Call) Return(_a0 *model.Task, _a1 error) *MockTaskService_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_CreateTask_Call) RunAndReturn(run func(string, model.TaskType, float64) (*model.Task, error)) *MockTaskService_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByDateRange provides a mock function with given fields: from, to
func (_m *MockTaskService) GetTasksByDateRange(from time.Time, to time.Time) ([]*model.Task, error) {
	ret := _m.Called(from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByDateRange")
	}

	var r0 []*model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) ([]*model.Task, error)); ok {
		return rf(from, to)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) []*model.Task); ok {
		r0 = rf(from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_GetTasksByDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByDateRange'
type MockTaskService_GetTasksByDateRange_Call struct {
	*mock.Call
}

// GetTasksByDateRange is a helper method to define mock.On call
//   - from time.Time
//   - to time.Time
func (_e *MockTaskService_Expecter) GetTasksByDateRange(from interface{}, to interface{}) *MockTaskService_GetTasksByDateRange_Call {
	return &MockTaskService_GetTasksByDateRange_Call{Call: _e.mock.On("GetTasksByDateRange", from, to)}
}

func (_c *MockTaskService_GetTasksByDateRange_Call) Run(run func(from time.Time, to time.Time)) *MockTaskService_GetTasksByDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Time))
	})
	return _c
}

func (_c *MockTaskService_GetTasksByDateRange_Call) Return(_a0 []*model.Task, _a1 error) *MockTaskService_GetTasksByDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_GetTasksByDateRange_Call) RunAndReturn(run func(time.Time, time.Time) ([]*model.Task, error)) *MockTaskService_GetTasksByDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByUserIDAndType provides a mock function with given fields: userID, taskType
func (_m *MockTaskService) GetTasksByUserIDAndType(userID string, taskType model.TaskType) ([]*model.Task, error) {
	ret := _m.Called(userID, taskType)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByUserIDAndType")
	}

	var r0 []*model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string, model.TaskType) ([]*model.Task, error)); ok {
		return rf(userID, taskType)
	}
	if rf, ok := ret.Get(0).(func(string, model.TaskType) []*model.Task); ok {
		r0 = rf(userID, taskType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string, model.TaskType) error); ok {
		r1 = rf(userID, taskType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_GetTasksByUserIDAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByUserIDAndType'
type MockTaskService_GetTasksByUserIDAndType_Call struct {
	*mock.Call
}

// GetTasksByUserIDAndType is a helper method to define mock.On call
//   - userID string
//   - taskType model.TaskType
func (_e *MockTaskService_Expecter) GetTasksByUserIDAndType(userID interface{}, taskType interface{}) *MockTaskService_GetTasksByUserIDAndType_Call {
	return &MockTaskService_GetTasksByUserIDAndType_Call{Call: _e.mock.On("GetTasksByUserIDAndType", userID, taskType)}
}

func (_c *MockTaskService_GetTasksByUserIDAndType_Call) Run(run func(userID string, taskType model.TaskType)) *MockTaskService_GetTasksByUserIDAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.TaskType))
	})
	return _c
}

func (_c *MockTaskService_GetTasksByUserIDAndType_Call) Return(_a0 []*model.Task, _a1 error) *MockTaskService_GetTasksByUserIDAndType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_GetTasksByUserIDAndType_Call) RunAndReturn(run func(string, model.TaskType) ([]*model.Task, error)) *MockTaskService_GetTasksByUserIDAndType_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksOfUser provides a mock function with given fields: userId
func (_m *MockTaskService) GetTasksOfUser(userId string) ([]*model.Task, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksOfUser")
	}

	var r0 []*model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*model.Task, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(string) []*model.Task); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_GetTasksOfUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksOfUser'
type MockTaskService_GetTasksOfUser_Call struct {
	*mock.Call
}

// GetTasksOfUser is a helper method to define mock.On call
//   - userId string
func (_e *MockTaskService_Expecter) GetTasksOfUser(userId interface{}) *MockTaskService_GetTasksOfUser_Call {
	return &MockTaskService_GetTasksOfUser_Call{Call: _e.mock.On("GetTasksOfUser", userId)}
}

func (_c *MockTaskService_GetTasksOfUser_Call) Run(run func(userId string)) *MockTaskService_GetTasksOfUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTaskService_GetTasksOfUser_Call) Return(_a0 []*model.Task, _a1 error) *MockTaskService_GetTasksOfUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_GetTasksOfUser_Call) RunAndReturn(run func(string) ([]*model.Task, error)) *MockTaskService_GetTasksOfUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
