name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  APP_ENV: github
  CONFIG_FOLDER: ${{ github.workspace }}/config

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: trading_ace_test
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d trading_ace_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Run migrations
        run: |
          go run migrations/main.go

      - name: Run tests and generate coverage report
        run: go test -coverprofile=coverage.out -v ./src/...

      - name: Check coverage
        run: |
          coverage=$(go tool cover -func=coverage.out | grep total: | awk '{print $3}' | sed 's/%//')
          echo "Coverage: $coverage%"
#          if [ "$(echo "$coverage < 60" | bc)" -eq 1 ]; then
#            echo "Coverage is below 60%. Failing the build."
#            exit 1
#          fi
